# Generated by Django 5.1.1 on 2024-09-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_alter_notice_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=800),
        ),
    ]
