# Generated by Django 5.1.1 on 2024-09-23 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('thumnail', models.ImageField(upload_to='%Y%m%d/')),
                ('place', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('FOOD', '음식'), ('GOODS', '굿즈'), ('EXPERIENCE', '체험')], max_length=10)),
                ('phonenum', models.IntegerField(unique=True)),
                ('is_opened', models.BooleanField(default=True)),
                ('Field', models.TextField(null=True)),
                ('is_show', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
