# Generated by Django 5.1.1 on 2024-09-23 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('thumnail', models.ImageField(upload_to='thumbnail')),
                ('place', models.CharField(choices=[('교육관', '교육관'), ('학문관', '학문관'), ('생활관', '생활관'), ('대강당', '대강당'), ('휴웃길', '휴웃길'), ('포스코관', '포스코관'), ('신세계관', '신세계관'), ('잔디광장', '잔디광장'), ('학관', '학관')], max_length=20)),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('음식', '음식'), ('굿즈', '굿즈'), ('체험', '체험'), ('학문관광장', '학문관광장'), ('스포츠트랙', '스포츠트랙')], max_length=10)),
                ('phonenum', models.IntegerField(unique=True)),
                ('is_opened', models.BooleanField(default=True)),
                ('Field', models.TextField(null=True)),
                ('is_show', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='menu_img')),
                ('is_vegan', models.CharField(choices=[('페스코', '페스코'), ('비건', '비건'), ('None', 'None')], default='None', max_length=10)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='booths.booths')),
            ],
        ),
    ]
