# Generated by Django 5.1.1 on 2024-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booth',
            name='notice_count',
            field=models.IntegerField(default=0),
        ),
    ]
