# Generated by Django 5.1.1 on 2024-09-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booths',
            name='thumnail',
            field=models.ImageField(upload_to='thumbnail'),
        ),
    ]
