# Generated by Django 5.1.1 on 2024-09-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_remove_booths_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booths',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
