# Generated by Django 5.1.1 on 2024-09-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0002_alter_booths_thumnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='menu_img')),
                ('is_vegan', models.BooleanField(default=False)),
            ],
        ),
    ]
