# Generated by Django 5.1.1 on 2024-10-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0004_booth_booth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='booth_category',
            field=models.CharField(blank=True, choices=[('기획부스', '기획부스'), ('권리팀부스', '권리팀부스'), ('대외협력팀부스', '대외협력팀부스')], max_length=10, null=True),
        ),
    ]
