# Generated by Django 3.2.25 on 2024-10-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0006_alter_booth_booth_category_alter_booth_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
    ]
