# Generated by Django 3.2.25 on 2024-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booths', '0007_alter_booth_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail'),
        ),
    ]
